# Generated by Django 6.0.4 on 2026-04-23 21:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Bitki Adı')),
                ('species', models.CharField(blank=True, max_length=100, verbose_name='Bilimsel Ad')),
                ('plant_type', models.CharField(choices=[('salon', 'Salon Bitkisi'), ('sukulent', 'Sukulent'), ('kaktus', 'Kaktüs'), ('tropikal', 'Tropikal'), ('erelti', 'Eğrelti Otu'), ('orkide', 'Orkide'), ('diger', 'Diğer')], default='salon', max_length=20, verbose_name='Tür')),
                ('location', models.CharField(blank=True, default='Salon', max_length=100, verbose_name='Konum')),
                ('water_frequency', models.CharField(choices=[('her_gun', 'Her Gün'), ('2_gunde', '2 Günde Bir'), ('3_gunde', '3 Günde Bir'), ('haftada', 'Haftada Bir'), ('2_haftada', '2 Haftada Bir'), ('ayda', 'Ayda Bir')], default='3_gunde', max_length=20, verbose_name='Sulama Sıklığı')),
                ('light_need', models.CharField(choices=[('tam_gunes', 'Tam Güneş'), ('dolayli', 'Dolaylı Güneş'), ('yari_golge', 'Yarı Gölge'), ('tam_golge', 'Tam Gölge')], default='dolayli', max_length=20, verbose_name='Işık İhtiyacı')),
                ('image', models.ImageField(blank=True, null=True, upload_to='plants/', verbose_name='Fotoğraf')),
                ('is_healthy', models.BooleanField(default=True, verbose_name='Sağlıklı mı?')),
                ('last_watered', models.DateTimeField(blank=True, null=True, verbose_name='Son Sulama')),
                ('last_fertilized', models.DateTimeField(blank=True, null=True, verbose_name='Son Gübreleme')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plants', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bitki',
                'verbose_name_plural': 'Bitkiler',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Not')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='bahce.plant')),
            ],
            options={
                'verbose_name': 'Not',
                'verbose_name_plural': 'Notlar',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('water', 'Sulama'), ('fertilize', 'Gübreleme'), ('repot', 'Saksı Değişimi'), ('clean', 'Yaprak Temizliği'), ('prune', 'Budama')], max_length=20, verbose_name='Görev Türü')),
                ('due_date', models.DateField(verbose_name='Görev Tarihi')),
                ('completed', models.BooleanField(default=False, verbose_name='Tamamlandı')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Tamamlanma Zamanı')),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='bahce.plant')),
            ],
            options={
                'verbose_name': 'Görev',
                'verbose_name_plural': 'Görevler',
                'ordering': ['due_date'],
            },
        ),
    ]
